language: 
sudo: required
services:
  - docker

before_install:
  - docker build -t quiglen3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true quiglen3/react-test npm test -- --coverage

after_success:
  - docker build -t quiglen3/docker-complex-worker ./worker
  - docker build -t quiglen3/docker-complex-server ./server
  - docker build -t quiglen3/docker-complex-nginx ./nginx
  - docker build -t quiglen3/docker-complex-client ./client

  - docker logout
  - echo "$docker_pwd" | docker login -u "$docker_id" --password-stdin

  - docker push quiglen3/docker-complex-worker
  - docker push quiglen3/docker-complex-server
  - docker push quiglen3/docker-complex-nginx
  - docker push quiglen3/docker-complex-client